server:
  port: 9999
  

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:        locator:          enabled: true
          lower-case-service-id: true
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
          - Path=/employee/**
        filters:
        - name: Hystrix
          args:
             name:  EMPLOYEE-SERVICE
             fallbackUri: forward:/employeeFallBack
      - id: PHARMACY-SERVICE
        uri: lb://PHARMACY-SERVICE
        predicates:
          - Path=/pharmacy/**
        
        filters:
        - name: Hystrix
          args:
             name:  PHARMACY-SERVICE
             fallbackUri: forward:/pharmacyFallBack

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
            
management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    eureka-server-port: 8761
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com: INFO